### ISSUE TITLE
UCERegion command removing loci from final results

### ISSUE THREAD

**Issue by michael-branstetter** [vhfsantos/CURE#11]
It has come to my attention that the UCERegion command that runs the SWSC method in parallel is removing some UCE loci from the final output. Have you noticed this issue? Can it be resolved?

**Comment by vhfsantos** [comment]
Hi Michael, 
this might be solved with the latest version [v1.0.5](https://github.com/vhfsantos/CURE/tree/v1.0.5).
Let me know

Cheers
